/**
 * Official phonetic reference for all 28 Arabic letters.
 * Source: Guide Complet de Prononciation Phonétique (Tanwin, voyelles courtes/longues).
 * French TTS strings are tuned for fr-FR-DeniseNeural — full names with -oun, never "Bé/Té".
 */

export type VowelTriple = { fatha: string; kasra: string; damma: string }

export type LetterPhonetics = {
  /** French TTS: full letter name with tanwin (e.g. Baoun). */
  nameFr: string
  nameEn: string
  nameAr: string
  short: VowelTriple
  long: VowelTriple
  tanwin: VowelTriple
  /** French TTS phrases for each sound (spoken on tap). */
  speakFr: {
    name: string
    shortFatha: string
    shortKasra: string
    shortDamma: string
    longAlif: string
    longYa: string
    longWaw: string
    tanwinAn: string
    tanwinIn: string
    tanwinUn: string
  }
}

export const LETTER_PHONETICS: Record<string, LetterPhonetics> = {
  alif: {
    nameFr: 'Alifoun',
    nameEn: 'Alif-un',
    nameAr: 'أَلِف',
    short: { fatha: 'a', kasra: 'i', damma: 'u' },
    long: { fatha: 'ā', kasra: 'ī', damma: 'ū' },
    tanwin: { fatha: 'an', kasra: 'in', damma: 'un' },
    speakFr: {
      name: 'Alifoun',
      shortFatha: 'a',
      shortKasra: 'i',
      shortDamma: 'ou',
      longAlif: 'â',
      longYa: 'î',
      longWaw: 'ou long',
      tanwinAn: 'an',
      tanwinIn: 'in',
      tanwinUn: 'oun',
    },
  },
  ba: {
    nameFr: 'Baoun',
    nameEn: "Bā'-un",
    nameAr: 'بَاء',
    short: { fatha: 'ba', kasra: 'bi', damma: 'bu' },
    long: { fatha: 'bā', kasra: 'bī', damma: 'bū' },
    tanwin: { fatha: 'ban', kasra: 'bin', damma: 'bun' },
    speakFr: {
      name: 'Baoun',
      shortFatha: 'ba',
      shortKasra: 'bi',
      shortDamma: 'bou',
      longAlif: 'bâ',
      longYa: 'bî',
      longWaw: 'bou long',
      tanwinAn: 'ban',
      tanwinIn: 'bin',
      tanwinUn: 'boun',
    },
  },
  ta: {
    nameFr: 'Taoun',
    nameEn: "Tā'-un",
    nameAr: 'تَاء',
    short: { fatha: 'ta', kasra: 'ti', damma: 'tu' },
    long: { fatha: 'tā', kasra: 'tī', damma: 'tū' },
    tanwin: { fatha: 'tan', kasra: 'tin', damma: 'tun' },
    speakFr: {
      name: 'Taoun',
      shortFatha: 'ta',
      shortKasra: 'ti',
      shortDamma: 'tou',
      longAlif: 'tâ',
      longYa: 'tî',
      longWaw: 'tou long',
      tanwinAn: 'tan',
      tanwinIn: 'tin',
      tanwinUn: 'toun',
    },
  },
  tha: {
    nameFr: 'Saaoun',
    nameEn: "Thā'-un",
    nameAr: 'ثَاء',
    short: { fatha: 'tha', kasra: 'thi', damma: 'thu' },
    long: { fatha: 'thā', kasra: 'thī', damma: 'thū' },
    tanwin: { fatha: 'than', kasra: 'thin', damma: 'thun' },
    speakFr: {
      name: 'Saaoun',
      shortFatha: 'tha',
      shortKasra: 'thi',
      shortDamma: 'thou',
      longAlif: 'thâ',
      longYa: 'thî',
      longWaw: 'thou long',
      tanwinAn: 'than',
      tanwinIn: 'thin',
      tanwinUn: 'thoun',
    },
  },
  jim: {
    nameFr: 'Djimoun',
    nameEn: 'Jīm-un',
    nameAr: 'جِيم',
    short: { fatha: 'ja', kasra: 'ji', damma: 'ju' },
    long: { fatha: 'jā', kasra: 'jī', damma: 'jū' },
    tanwin: { fatha: 'jan', kasra: 'jin', damma: 'jun' },
    speakFr: {
      name: 'Djimoun',
      shortFatha: 'dja',
      shortKasra: 'dji',
      shortDamma: 'djou',
      longAlif: 'djâ',
      longYa: 'djî',
      longWaw: 'djou long',
      tanwinAn: 'djan',
      tanwinIn: 'djin',
      tanwinUn: 'djoun',
    },
  },
  ha: {
    nameFr: 'Ha-un',
    nameEn: 'Ha-un',
    nameAr: 'حَاء',
    short: { fatha: 'ḥa', kasra: 'ḥi', damma: 'ḥu' },
    long: { fatha: 'ḥā', kasra: 'ḥī', damma: 'ḥū' },
    tanwin: { fatha: 'ḥan', kasra: 'ḥin', damma: 'ḥun' },
    speakFr: {
      name: 'Haaoun',
      shortFatha: 'ha aspiré',
      shortKasra: 'hi aspiré',
      shortDamma: 'hou aspiré',
      longAlif: 'hâ aspiré',
      longYa: 'hî aspiré',
      longWaw: 'hou long aspiré',
      tanwinAn: 'han aspiré',
      tanwinIn: 'hin aspiré',
      tanwinUn: 'houn aspiré',
    },
  },
  kha: {
    nameFr: 'Khaoun',
    nameEn: 'Khoun',
    nameAr: 'خَاء',
    short: { fatha: 'kha', kasra: 'khi', damma: 'khu' },
    long: { fatha: 'khā', kasra: 'khī', damma: 'khū' },
    tanwin: { fatha: 'khan', kasra: 'khin', damma: 'khun' },
    speakFr: {
      name: 'Khaoun',
      shortFatha: 'kha',
      shortKasra: 'khi',
      shortDamma: 'khou',
      longAlif: 'khâ',
      longYa: 'khî',
      longWaw: 'khou long',
      tanwinAn: 'khan',
      tanwinIn: 'khin',
      tanwinUn: 'khoun',
    },
  },
  dal: {
    nameFr: 'Daloun',
    nameEn: 'Dāl-un',
    nameAr: 'دَال',
    short: { fatha: 'da', kasra: 'di', damma: 'du' },
    long: { fatha: 'dā', kasra: 'dī', damma: 'dū' },
    tanwin: { fatha: 'dan', kasra: 'din', damma: 'dun' },
    speakFr: {
      name: 'Daloun',
      shortFatha: 'da',
      shortKasra: 'di',
      shortDamma: 'dou',
      longAlif: 'dâ',
      longYa: 'dî',
      longWaw: 'dou long',
      tanwinAn: 'dan',
      tanwinIn: 'din',
      tanwinUn: 'doun',
    },
  },
  dhal: {
    nameFr: 'Zaloon',
    nameEn: 'Zaloon',
    nameAr: 'ذَال',
    short: { fatha: 'dha', kasra: 'dhi', damma: 'dhu' },
    long: { fatha: 'dhā', kasra: 'dhī', damma: 'dhū' },
    tanwin: { fatha: 'dhan', kasra: 'dhin', damma: 'dhun' },
    speakFr: {
      name: 'Zaloon',
      shortFatha: 'dha',
      shortKasra: 'dhi',
      shortDamma: 'dhou',
      longAlif: 'dhâ',
      longYa: 'dhî',
      longWaw: 'dhou long',
      tanwinAn: 'dhan',
      tanwinIn: 'dhin',
      tanwinUn: 'dhoun',
    },
  },
  ra: {
    nameFr: 'Rlaoune',
    nameEn: 'Raoun',
    nameAr: 'رَاء',
    short: { fatha: 'ra', kasra: 'ri', damma: 'ru' },
    long: { fatha: 'rā', kasra: 'rī', damma: 'rū' },
    tanwin: { fatha: 'ran', kasra: 'rin', damma: 'run' },
    speakFr: {
      name: 'Rlaoune',
      shortFatha: 'ra',
      shortKasra: 'ri',
      shortDamma: 'rou',
      longAlif: 'râ',
      longYa: 'rî',
      longWaw: 'rou long',
      tanwinAn: 'ran',
      tanwinIn: 'rin',
      tanwinUn: 'roun',
    },
  },
  zay: {
    nameFr: 'Zayoun',
    nameEn: 'Zāy-un',
    nameAr: 'زَاي',
    short: { fatha: 'za', kasra: 'zi', damma: 'zu' },
    long: { fatha: 'zā', kasra: 'zī', damma: 'zū' },
    tanwin: { fatha: 'zan', kasra: 'zin', damma: 'zun' },
    speakFr: {
      name: 'Zayoun',
      shortFatha: 'za',
      shortKasra: 'zi',
      shortDamma: 'zou',
      longAlif: 'zâ',
      longYa: 'zî',
      longWaw: 'zou long',
      tanwinAn: 'zan',
      tanwinIn: 'zin',
      tanwinUn: 'zoun',
    },
  },
  sin: {
    nameFr: 'Sinoun',
    nameEn: 'Sīn-un',
    nameAr: 'سِين',
    short: { fatha: 'sa', kasra: 'si', damma: 'su' },
    long: { fatha: 'sā', kasra: 'sī', damma: 'sū' },
    tanwin: { fatha: 'san', kasra: 'sin', damma: 'sun' },
    speakFr: {
      name: 'Sinoun',
      shortFatha: 'sa',
      shortKasra: 'si',
      shortDamma: 'sou',
      longAlif: 'sâ',
      longYa: 'sî',
      longWaw: 'sou long',
      tanwinAn: 'san',
      tanwinIn: 'sin',
      tanwinUn: 'soun',
    },
  },
  shin: {
    nameFr: 'Chinoun',
    nameEn: 'Shīn-un',
    nameAr: 'شِين',
    short: { fatha: 'sha', kasra: 'shi', damma: 'shu' },
    long: { fatha: 'shā', kasra: 'shī', damma: 'shū' },
    tanwin: { fatha: 'shan', kasra: 'shin', damma: 'shun' },
    speakFr: {
      name: 'Chinoun',
      shortFatha: 'cha',
      shortKasra: 'chi',
      shortDamma: 'chou',
      longAlif: 'châ',
      longYa: 'chî',
      longWaw: 'chou long',
      tanwinAn: 'chan',
      tanwinIn: 'chin',
      tanwinUn: 'choun',
    },
  },
  sad: {
    nameFr: 'Sodoun',
    nameEn: 'Ṣād-un',
    nameAr: 'صَاد',
    short: { fatha: 'ṣa', kasra: 'ṣi', damma: 'ṣu' },
    long: { fatha: 'ṣā', kasra: 'ṣī', damma: 'ṣū' },
    tanwin: { fatha: 'ṣan', kasra: 'ṣin', damma: 'ṣun' },
    speakFr: {
      name: 'Sodoun',
      shortFatha: 'ssa',
      shortKasra: 'ssi',
      shortDamma: 'ssou',
      longAlif: 'ssâ',
      longYa: 'ssî',
      longWaw: 'ssou long',
      tanwinAn: 'ssan',
      tanwinIn: 'ssin',
      tanwinUn: 'ssoun',
    },
  },
  dad: {
    nameFr: 'Dodoun',
    nameEn: 'Ḍād-un',
    nameAr: 'ضَاد',
    short: { fatha: 'ḍa', kasra: 'ḍi', damma: 'ḍu' },
    long: { fatha: 'ḍā', kasra: 'ḍī', damma: 'ḍū' },
    tanwin: { fatha: 'ḍan', kasra: 'ḍin', damma: 'ḍun' },
    speakFr: {
      name: 'Dodoun',
      shortFatha: 'dda',
      shortKasra: 'ddi',
      shortDamma: 'ddou',
      longAlif: 'ddâ',
      longYa: 'ddî',
      longWaw: 'ddou long',
      tanwinAn: 'ddan',
      tanwinIn: 'ddin',
      tanwinUn: 'ddoun',
    },
  },
  taa: {
    nameFr: 'Tooun',
    nameEn: 'Ṭāʾ-un',
    nameAr: 'طَاء',
    short: { fatha: 'ṭa', kasra: 'ṭi', damma: 'ṭu' },
    long: { fatha: 'ṭā', kasra: 'ṭī', damma: 'ṭū' },
    tanwin: { fatha: 'ṭan', kasra: 'ṭin', damma: 'ṭun' },
    speakFr: {
      name: 'Tooun',
      shortFatha: 'tta',
      shortKasra: 'tti',
      shortDamma: 'ttou',
      longAlif: 'ttâ',
      longYa: 'ttî',
      longWaw: 'ttou long',
      tanwinAn: 'ttan',
      tanwinIn: 'ttin',
      tanwinUn: 'ttoun',
    },
  },
  zaa: {
    nameFr: 'Zooun',
    nameEn: 'Ẓāʾ-un',
    nameAr: 'ظَاء',
    short: { fatha: 'ẓa', kasra: 'ẓi', damma: 'ẓu' },
    long: { fatha: 'ẓā', kasra: 'ẓī', damma: 'ẓū' },
    tanwin: { fatha: 'ẓan', kasra: 'ẓin', damma: 'ẓun' },
    speakFr: {
      name: 'Zooun',
      shortFatha: 'zza',
      shortKasra: 'zzi',
      shortDamma: 'zzou',
      longAlif: 'zzâ',
      longYa: 'zzî',
      longWaw: 'zzou long',
      tanwinAn: 'zzan',
      tanwinIn: 'zzin',
      tanwinUn: 'zzoun',
    },
  },
  ayn: {
    nameFr: 'Aïnoun',
    nameEn: "'Ayn-un",
    nameAr: 'عَيْن',
    short: { fatha: "'a", kasra: "'i", damma: "'u" },
    long: { fatha: "'ā", kasra: "'ī", damma: "'ū" },
    tanwin: { fatha: "'an", kasra: "'in", damma: "'un" },
    speakFr: {
      name: 'Aïnoun',
      shortFatha: 'aïn',
      shortKasra: 'ï',
      shortDamma: 'ou aïn',
      longAlif: 'aïn long',
      longYa: 'ï long',
      longWaw: 'ou aïn long',
      tanwinAn: 'aïn an',
      tanwinIn: 'ïn',
      tanwinUn: 'aïn oun',
    },
  },
  ghayn: {
    nameFr: 'Gaïnoun',
    nameEn: 'Ghayn-un',
    nameAr: 'غَيْن',
    short: { fatha: 'gha', kasra: 'ghi', damma: 'ghu' },
    long: { fatha: 'ghā', kasra: 'ghī', damma: 'ghū' },
    tanwin: { fatha: 'ghan', kasra: 'ghin', damma: 'ghun' },
    speakFr: {
      name: 'Gaïnoun',
      shortFatha: 'gha',
      shortKasra: 'ghi',
      shortDamma: 'ghou',
      longAlif: 'ghâ',
      longYa: 'ghî',
      longWaw: 'ghou long',
      tanwinAn: 'ghan',
      tanwinIn: 'ghin',
      tanwinUn: 'ghoun',
    },
  },
  fa: {
    nameFr: 'Faoun',
    nameEn: "Fā'-un",
    nameAr: 'فَاء',
    short: { fatha: 'fa', kasra: 'fi', damma: 'fu' },
    long: { fatha: 'fā', kasra: 'fī', damma: 'fū' },
    tanwin: { fatha: 'fan', kasra: 'fin', damma: 'fun' },
    speakFr: {
      name: 'Faoun',
      shortFatha: 'fa',
      shortKasra: 'fi',
      shortDamma: 'fou',
      longAlif: 'fâ',
      longYa: 'fî',
      longWaw: 'fou long',
      tanwinAn: 'fan',
      tanwinIn: 'fin',
      tanwinUn: 'foun',
    },
  },
  qaf: {
    nameFr: 'Kofoun',
    nameEn: 'Qāf-un',
    nameAr: 'قَاف',
    short: { fatha: 'qa', kasra: 'qi', damma: 'qu' },
    long: { fatha: 'qā', kasra: 'qī', damma: 'qū' },
    tanwin: { fatha: 'qan', kasra: 'qin', damma: 'qun' },
    speakFr: {
      name: 'Kofoun',
      shortFatha: 'kof',
      shortKasra: 'ki kof',
      shortDamma: 'kou kof',
      longAlif: 'kofâ',
      longYa: 'kî kof',
      longWaw: 'kou long kof',
      tanwinAn: 'kofan',
      tanwinIn: 'kin kof',
      tanwinUn: 'kofoun',
    },
  },
  kaf: {
    nameFr: 'Kafoun',
    nameEn: 'Kāf-un',
    nameAr: 'كَاف',
    short: { fatha: 'ka', kasra: 'ki', damma: 'ku' },
    long: { fatha: 'kā', kasra: 'kī', damma: 'kū' },
    tanwin: { fatha: 'kan', kasra: 'kin', damma: 'kun' },
    speakFr: {
      name: 'Kafoun',
      shortFatha: 'ka',
      shortKasra: 'ki',
      shortDamma: 'kou',
      longAlif: 'kâ',
      longYa: 'kî',
      longWaw: 'kou long',
      tanwinAn: 'kan',
      tanwinIn: 'kin',
      tanwinUn: 'koun',
    },
  },
  lam: {
    nameFr: 'Lamoun',
    nameEn: 'Lām-un',
    nameAr: 'لَام',
    short: { fatha: 'la', kasra: 'li', damma: 'lu' },
    long: { fatha: 'lā', kasra: 'lī', damma: 'lū' },
    tanwin: { fatha: 'lan', kasra: 'lin', damma: 'lun' },
    speakFr: {
      name: 'Lamoun',
      shortFatha: 'la',
      shortKasra: 'li',
      shortDamma: 'lou',
      longAlif: 'lâ',
      longYa: 'lî',
      longWaw: 'lou long',
      tanwinAn: 'lan',
      tanwinIn: 'lin',
      tanwinUn: 'loun',
    },
  },
  mim: {
    nameFr: 'Mimoun',
    nameEn: 'Mīm-un',
    nameAr: 'مِيم',
    short: { fatha: 'ma', kasra: 'mi', damma: 'mu' },
    long: { fatha: 'mā', kasra: 'mī', damma: 'mū' },
    tanwin: { fatha: 'man', kasra: 'min', damma: 'mun' },
    speakFr: {
      name: 'Mimoun',
      shortFatha: 'ma',
      shortKasra: 'mi',
      shortDamma: 'mou',
      longAlif: 'mâ',
      longYa: 'mî',
      longWaw: 'mou long',
      tanwinAn: 'man',
      tanwinIn: 'min',
      tanwinUn: 'moun',
    },
  },
  nun: {
    nameFr: 'Nounoun',
    nameEn: 'Nūn-un',
    nameAr: 'نُون',
    short: { fatha: 'na', kasra: 'ni', damma: 'nu' },
    long: { fatha: 'nā', kasra: 'nī', damma: 'nū' },
    tanwin: { fatha: 'nan', kasra: 'nin', damma: 'nun' },
    speakFr: {
      name: 'Nounoun',
      shortFatha: 'na',
      shortKasra: 'ni',
      shortDamma: 'nou',
      longAlif: 'nâ',
      longYa: 'nî',
      longWaw: 'nou long',
      tanwinAn: 'nan',
      tanwinIn: 'nin',
      tanwinUn: 'noun',
    },
  },
  ha2: {
    nameFr: 'Haoun',
    nameEn: "Hā'-un",
    nameAr: 'هَاء',
    short: { fatha: 'ha', kasra: 'hi', damma: 'hu' },
    long: { fatha: 'hā', kasra: 'hī', damma: 'hū' },
    tanwin: { fatha: 'han', kasra: 'hin', damma: 'hun' },
    speakFr: {
      // Final e stops the French voice from swallowing the initial "Ha".
      name: 'Haoune',
      shortFatha: 'ha',
      shortKasra: 'hi',
      shortDamma: 'hou',
      longAlif: 'hâ léger',
      longYa: 'hî léger',
      longWaw: 'hou long léger',
      tanwinAn: 'han',
      tanwinIn: 'hin',
      tanwinUn: 'houn',
    },
  },
  waw: {
    nameFr: 'Waoun',
    nameEn: 'Wāw-un',
    nameAr: 'وَاو',
    short: { fatha: 'wa', kasra: 'wi', damma: 'wu' },
    long: { fatha: 'wā', kasra: 'wī', damma: 'wū' },
    tanwin: { fatha: 'wan', kasra: 'win', damma: 'wun' },
    speakFr: {
      name: 'Waoun',
      shortFatha: 'wa',
      shortKasra: 'wi',
      shortDamma: 'wou',
      longAlif: 'wâ',
      longYa: 'wî',
      longWaw: 'wou long',
      tanwinAn: 'wan',
      tanwinIn: 'win',
      tanwinUn: 'woun',
    },
  },
  ya: {
    nameFr: 'Yaoun',
    nameEn: "Yā'-un",
    nameAr: 'يَاء',
    short: { fatha: 'ya', kasra: 'yi', damma: 'yu' },
    long: { fatha: 'yā', kasra: 'yī', damma: 'yū' },
    tanwin: { fatha: 'yan', kasra: 'yin', damma: 'yun' },
    speakFr: {
      name: 'Yaoun',
      shortFatha: 'ya',
      shortKasra: 'yi',
      shortDamma: 'you',
      longAlif: 'yâ',
      longYa: 'yî',
      longWaw: 'you long',
      tanwinAn: 'yan',
      tanwinIn: 'yin',
      tanwinUn: 'youn',
    },
  },
}

/** Full official name with tanwin for display (e.g. Bā'-un). */
export function letterNomComplet(letterId: string): string {
  return LETTER_PHONETICS[letterId]?.nameEn ?? ''
}

export type VowelFormKey =
  | 'shortFatha'
  | 'shortKasra'
  | 'shortDamma'
  | 'longAlif'
  | 'longYa'
  | 'longWaw'
  | 'tanwinAn'
  | 'tanwinIn'
  | 'tanwinUn'

/** French TTS phrase for a vowel/tanwin form of a letter. */
export function letterFormSpeech(letterId: string, form: VowelFormKey): string {
  const p = LETTER_PHONETICS[letterId]
  if (!p) return ''
  return p.speakFr[form]
}

/** Map RulesView form keys to phonetics keys. */
export const FORM_KEY_TO_SPEECH: Record<string, import('./letter-phonetics').VowelFormKey> = {
  fatha: 'shortFatha',
  kasra: 'shortKasra',
  damma: 'shortDamma',
  sukun: 'shortFatha', // sukun: letter alone, use fatha base sound
  aa: 'longAlif',
  ii: 'longYa',
  uu: 'longWaw',
  an: 'tanwinAn',
  in: 'tanwinIn',
  un: 'tanwinUn',
}
